name: Create Release Candidate

on:
    workflow_dispatch:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

jobs:
    build:
        name: Create release candidate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              name: Create Release candidate
              run: gh release create "${GITHUB_REF#refs/*/}" -t "$(grep name config/version.php | awk -F "'" '{print $4}')" -p --notes-file RELEASE_NOTES.md
